name: Build and push dev image

on:
  push:
    branches:
      - dev
    # Trigger the workflow on push to the 'dev' branch

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    # The runner OS

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # Checkout the repository code

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        # Login to Docker Hub using stored secrets for Docker username and token

      - name: Build image
        run: |
          docker image build -t ayazid/simplewebdev -f Dockerfile.dev .
        # Build the Docker image with a tag 'ayazid/simplewebdev' using Dockerfile.dev

      - name: Push image
        run: |
          docker image push ayazid/simplewebdev
        # Push the image to Docker Hub with the same tag
