name: Deploy application image

on:
  pull_request:
    types:
      - closed
    branches:
      - master
jobs:
  deploy-app:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: docker image build -t aya-zid/simplewebprod .
      - run: docker image push aya-zid/simplewebprod

